env:
    - GO111MODULE=on
  
  builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
  checksum:
    name_template: '{{ .ProjectName }}_checksums.txt'
  changelog:
    sort: asc
    filters:
      exclude:
      - '^ci:'
      - '^chore:'
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
  
  archives:
    - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
      replacements:
        darwin: Darwin
        linux: Linux
        386: i386
        amd64: x86_64
      files:
        - none*